### ISSUE TITLE
.gitignoreを作りましょう

### ISSUE THREAD

**Issue by sakairuh** [sminami/spark-simple-app#1]

**Comment by sminami** [comment]
土曜やる

**Comment by sakairuh** [comment]
https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Comment by sminami** [comment]
1. .gitignore作成
2. >git rm -r --cached .
　でファイル残しつつ一旦全部管理対象から外す
3. 管理対象のファイルをaddし、commitのちpush

**Comment by sminami** [comment]
commitメッセージにissue番号紐付け忘れたので、commitメッセージ修正した
